---
title: "A Test Drive of Flexdashboard"
output: flexdashboard::flex_dashboard
---

```{r load, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(GGally)
library(plotly)
```

Basic Layout
==============

One Column {data-width=200}
--------------

### Chart A

```{r}
ggplotly(qplot(mtcars$cyl) + labs(x = ""))
```

### A Gauge!

```{r}
gauge(
  value = round(mean(mtcars$cyl == 6) * 100),
  min = 0, max = 100,
  symbol = "%",
  label = "6-cylinder cars"
)
```


Another Column
--------------

### Chart B

```{r}
ggplotly(GGally::ggpairs(mtcars[,1:4]))
```


Row-Based Layout {data-orientation=rows}
==============

One Row
--------------

### Wide Chart

```{r}
ggplotly(qplot(mtcars$wt))
```

Another Row
--------------

### Chart 1

```{r}
ggplotly(qplot(mtcars$wt, mtcars$mpg))
```


### Chart 2

```{r}
ggplotly(qplot(mtcars$wt, mtcars$disp))
```
 
### Chart 3

```{r}
ggplotly(qplot(mtcars$wt, mtcars$hp))
```


Tabsets {data-navmenu='More Complex Layouts'}
==============

Single Tabset Column {.tabset}
--------------

### Tab Chart A

```{r}
ggplotly(qplot(mtcars$mpg,  geom = "dotplot"))
```

### Tab Chart B

```{r}
ggplotly(qplot(mtcars$wt,   geom = "dotplot"))
```

### Tab Chart C
```{r}
ggplotly(qplot(mtcars$disp, geom = "dotplot"))
```


Tabsets with Fade Effect {data-navmenu='More Complex Layouts'}
==============

Single Tabset Column {.tabset .tabset-fade}
--------------

### Tab Chart 1

```{r}
ggplotly(qplot(wt, mpg, data = mtcars, color = factor(cyl)))
```

### Tab Chart 2

```{r}
ggplotly(qplot(disp, mpg, data = mtcars, color = factor(cyl)))
```

### Tab Chart 3
```{r}
ggplotly(qplot(hp, mpg, data = mtcars, color = factor(cyl)))
```

